/* soapClient.cpp
   Generated by gSOAP 2.8.29 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.29 2019-10-25 09:28:11 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Counts(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Counts *ns1__Counts, _ns1__CountsResponse &ns1__CountsResponse)
{	struct __ns1__Counts soap_tmp___ns1__Counts;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/Counts";
	soap_tmp___ns1__Counts.ns1__Counts = ns1__Counts;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Counts(soap, &soap_tmp___ns1__Counts);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Counts(soap, &soap_tmp___ns1__Counts, "-ns1:Counts", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Counts(soap, &soap_tmp___ns1__Counts, "-ns1:Counts", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__CountsResponse)
		return soap_closesock(soap);
	ns1__CountsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CountsResponse.soap_get(soap, "ns1:CountsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAlarmsSinceLastQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAlarmsSinceLastQuery *ns1__GetAlarmsSinceLastQuery, _ns1__GetAlarmsSinceLastQueryResponse &ns1__GetAlarmsSinceLastQueryResponse)
{	struct __ns1__GetAlarmsSinceLastQuery soap_tmp___ns1__GetAlarmsSinceLastQuery;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetAlarmsSinceLastQuery";
	soap_tmp___ns1__GetAlarmsSinceLastQuery.ns1__GetAlarmsSinceLastQuery = ns1__GetAlarmsSinceLastQuery;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAlarmsSinceLastQuery(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAlarmsSinceLastQuery(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery, "-ns1:GetAlarmsSinceLastQuery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAlarmsSinceLastQuery(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery, "-ns1:GetAlarmsSinceLastQuery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAlarmsSinceLastQueryResponse)
		return soap_closesock(soap);
	ns1__GetAlarmsSinceLastQueryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAlarmsSinceLastQueryResponse.soap_get(soap, "ns1:GetAlarmsSinceLastQueryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAlarms(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAlarms *ns1__GetAlarms, _ns1__GetAlarmsResponse &ns1__GetAlarmsResponse)
{	struct __ns1__GetAlarms soap_tmp___ns1__GetAlarms;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetAlarms";
	soap_tmp___ns1__GetAlarms.ns1__GetAlarms = ns1__GetAlarms;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAlarms(soap, &soap_tmp___ns1__GetAlarms);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAlarms(soap, &soap_tmp___ns1__GetAlarms, "-ns1:GetAlarms", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAlarms(soap, &soap_tmp___ns1__GetAlarms, "-ns1:GetAlarms", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAlarmsResponse)
		return soap_closesock(soap);
	ns1__GetAlarmsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAlarmsResponse.soap_get(soap, "ns1:GetAlarmsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__MountedMolds(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__MountedMolds *ns1__MountedMolds, _ns1__MountedMoldsResponse &ns1__MountedMoldsResponse)
{	struct __ns1__MountedMolds soap_tmp___ns1__MountedMolds;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/MountedMolds";
	soap_tmp___ns1__MountedMolds.ns1__MountedMolds = ns1__MountedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__MountedMolds(soap, &soap_tmp___ns1__MountedMolds);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__MountedMolds(soap, &soap_tmp___ns1__MountedMolds, "-ns1:MountedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__MountedMolds(soap, &soap_tmp___ns1__MountedMolds, "-ns1:MountedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__MountedMoldsResponse)
		return soap_closesock(soap);
	ns1__MountedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MountedMoldsResponse.soap_get(soap, "ns1:MountedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Measures(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Measures *ns1__Measures, _ns1__MeasuresResponse &ns1__MeasuresResponse)
{	struct __ns1__Measures soap_tmp___ns1__Measures;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/Measures";
	soap_tmp___ns1__Measures.ns1__Measures = ns1__Measures;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Measures(soap, &soap_tmp___ns1__Measures);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Measures(soap, &soap_tmp___ns1__Measures, "-ns1:Measures", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Measures(soap, &soap_tmp___ns1__Measures, "-ns1:Measures", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__MeasuresResponse)
		return soap_closesock(soap);
	ns1__MeasuresResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MeasuresResponse.soap_get(soap, "ns1:MeasuresResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CumulCounts(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__CumulCounts *ns1__CumulCounts, _ns1__CumulCountsResponse &ns1__CumulCountsResponse)
{	struct __ns1__CumulCounts soap_tmp___ns1__CumulCounts;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/CumulCounts";
	soap_tmp___ns1__CumulCounts.ns1__CumulCounts = ns1__CumulCounts;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__CumulCounts(soap, &soap_tmp___ns1__CumulCounts);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CumulCounts(soap, &soap_tmp___ns1__CumulCounts, "-ns1:CumulCounts", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CumulCounts(soap, &soap_tmp___ns1__CumulCounts, "-ns1:CumulCounts", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__CumulCountsResponse)
		return soap_closesock(soap);
	ns1__CumulCountsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CumulCountsResponse.soap_get(soap, "ns1:CumulCountsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReadenMolds(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ReadenMolds *ns1__ReadenMolds, _ns1__ReadenMoldsResponse &ns1__ReadenMoldsResponse)
{	struct __ns1__ReadenMolds soap_tmp___ns1__ReadenMolds;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ReadenMolds";
	soap_tmp___ns1__ReadenMolds.ns1__ReadenMolds = ns1__ReadenMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ReadenMolds(soap, &soap_tmp___ns1__ReadenMolds);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReadenMolds(soap, &soap_tmp___ns1__ReadenMolds, "-ns1:ReadenMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReadenMolds(soap, &soap_tmp___ns1__ReadenMolds, "-ns1:ReadenMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ReadenMoldsResponse)
		return soap_closesock(soap);
	ns1__ReadenMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ReadenMoldsResponse.soap_get(soap, "ns1:ReadenMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__EjectedMolds(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__EjectedMolds *ns1__EjectedMolds, _ns1__EjectedMoldsResponse &ns1__EjectedMoldsResponse)
{	struct __ns1__EjectedMolds soap_tmp___ns1__EjectedMolds;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/EjectedMolds";
	soap_tmp___ns1__EjectedMolds.ns1__EjectedMolds = ns1__EjectedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__EjectedMolds(soap, &soap_tmp___ns1__EjectedMolds);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__EjectedMolds(soap, &soap_tmp___ns1__EjectedMolds, "-ns1:EjectedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__EjectedMolds(soap, &soap_tmp___ns1__EjectedMolds, "-ns1:EjectedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__EjectedMoldsResponse)
		return soap_closesock(soap);
	ns1__EjectedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__EjectedMoldsResponse.soap_get(soap, "ns1:EjectedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetMoldsInSampleTable(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetMoldsInSampleTable *ns1__GetMoldsInSampleTable, _ns1__GetMoldsInSampleTableResponse &ns1__GetMoldsInSampleTableResponse)
{	struct __ns1__GetMoldsInSampleTable soap_tmp___ns1__GetMoldsInSampleTable;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetMoldsInSampleTable";
	soap_tmp___ns1__GetMoldsInSampleTable.ns1__GetMoldsInSampleTable = ns1__GetMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetMoldsInSampleTable(soap, &soap_tmp___ns1__GetMoldsInSampleTable);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetMoldsInSampleTable(soap, &soap_tmp___ns1__GetMoldsInSampleTable, "-ns1:GetMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetMoldsInSampleTable(soap, &soap_tmp___ns1__GetMoldsInSampleTable, "-ns1:GetMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__GetMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetMoldsInSampleTableResponse.soap_get(soap, "ns1:GetMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeMountedMolds(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeMountedMolds *ns1__ChangeMountedMolds, _ns1__ChangeMountedMoldsResponse &ns1__ChangeMountedMoldsResponse)
{	struct __ns1__ChangeMountedMolds soap_tmp___ns1__ChangeMountedMolds;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeMountedMolds";
	soap_tmp___ns1__ChangeMountedMolds.ns1__ChangeMountedMolds = ns1__ChangeMountedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeMountedMolds(soap, &soap_tmp___ns1__ChangeMountedMolds);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeMountedMolds(soap, &soap_tmp___ns1__ChangeMountedMolds, "-ns1:ChangeMountedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeMountedMolds(soap, &soap_tmp___ns1__ChangeMountedMolds, "-ns1:ChangeMountedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeMountedMoldsResponse)
		return soap_closesock(soap);
	ns1__ChangeMountedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeMountedMoldsResponse.soap_get(soap, "ns1:ChangeMountedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AddEjectedMolds(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AddEjectedMolds *ns1__AddEjectedMolds, _ns1__AddEjectedMoldsResponse &ns1__AddEjectedMoldsResponse)
{	struct __ns1__AddEjectedMolds soap_tmp___ns1__AddEjectedMolds;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/AddEjectedMolds";
	soap_tmp___ns1__AddEjectedMolds.ns1__AddEjectedMolds = ns1__AddEjectedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__AddEjectedMolds(soap, &soap_tmp___ns1__AddEjectedMolds);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AddEjectedMolds(soap, &soap_tmp___ns1__AddEjectedMolds, "-ns1:AddEjectedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AddEjectedMolds(soap, &soap_tmp___ns1__AddEjectedMolds, "-ns1:AddEjectedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__AddEjectedMoldsResponse)
		return soap_closesock(soap);
	ns1__AddEjectedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__AddEjectedMoldsResponse.soap_get(soap, "ns1:AddEjectedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__EraseMoldsInSampleTable(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__EraseMoldsInSampleTable *ns1__EraseMoldsInSampleTable, _ns1__EraseMoldsInSampleTableResponse &ns1__EraseMoldsInSampleTableResponse)
{	struct __ns1__EraseMoldsInSampleTable soap_tmp___ns1__EraseMoldsInSampleTable;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/EraseMoldsInSampleTable";
	soap_tmp___ns1__EraseMoldsInSampleTable.ns1__EraseMoldsInSampleTable = ns1__EraseMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__EraseMoldsInSampleTable(soap, &soap_tmp___ns1__EraseMoldsInSampleTable);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__EraseMoldsInSampleTable(soap, &soap_tmp___ns1__EraseMoldsInSampleTable, "-ns1:EraseMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__EraseMoldsInSampleTable(soap, &soap_tmp___ns1__EraseMoldsInSampleTable, "-ns1:EraseMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__EraseMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__EraseMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__EraseMoldsInSampleTableResponse.soap_get(soap, "ns1:EraseMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeMoldsInSampleTable(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeMoldsInSampleTable *ns1__ChangeMoldsInSampleTable, _ns1__ChangeMoldsInSampleTableResponse &ns1__ChangeMoldsInSampleTableResponse)
{	struct __ns1__ChangeMoldsInSampleTable soap_tmp___ns1__ChangeMoldsInSampleTable;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeMoldsInSampleTable";
	soap_tmp___ns1__ChangeMoldsInSampleTable.ns1__ChangeMoldsInSampleTable = ns1__ChangeMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeMoldsInSampleTable(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeMoldsInSampleTable(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable, "-ns1:ChangeMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeMoldsInSampleTable(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable, "-ns1:ChangeMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__ChangeMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeMoldsInSampleTableResponse.soap_get(soap, "ns1:ChangeMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVersions(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetVersions *ns1__GetVersions, _ns1__GetVersionsResponse &ns1__GetVersionsResponse)
{	struct __ns1__GetVersions soap_tmp___ns1__GetVersions;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetVersions";
	soap_tmp___ns1__GetVersions.ns1__GetVersions = ns1__GetVersions;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetVersions(soap, &soap_tmp___ns1__GetVersions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetVersions(soap, &soap_tmp___ns1__GetVersions, "-ns1:GetVersions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetVersions(soap, &soap_tmp___ns1__GetVersions, "-ns1:GetVersions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetVersionsResponse)
		return soap_closesock(soap);
	ns1__GetVersionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetVersionsResponse.soap_get(soap, "ns1:GetVersionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeSamples(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeSamples *ns1__ChangeSamples, _ns1__ChangeSamplesResponse &ns1__ChangeSamplesResponse)
{	struct __ns1__ChangeSamples soap_tmp___ns1__ChangeSamples;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeSamples";
	soap_tmp___ns1__ChangeSamples.ns1__ChangeSamples = ns1__ChangeSamples;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeSamples(soap, &soap_tmp___ns1__ChangeSamples);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeSamples(soap, &soap_tmp___ns1__ChangeSamples, "-ns1:ChangeSamples", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeSamples(soap, &soap_tmp___ns1__ChangeSamples, "-ns1:ChangeSamples", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeSamplesResponse)
		return soap_closesock(soap);
	ns1__ChangeSamplesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeSamplesResponse.soap_get(soap, "ns1:ChangeSamplesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Counts_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Counts *ns1__Counts, _ns1__CountsResponse &ns1__CountsResponse)
{	struct __ns1__Counts_ soap_tmp___ns1__Counts_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/Counts";
	soap_tmp___ns1__Counts_.ns1__Counts = ns1__Counts;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Counts_(soap, &soap_tmp___ns1__Counts_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Counts_(soap, &soap_tmp___ns1__Counts_, "-ns1:Counts", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Counts_(soap, &soap_tmp___ns1__Counts_, "-ns1:Counts", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__CountsResponse)
		return soap_closesock(soap);
	ns1__CountsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CountsResponse.soap_get(soap, "ns1:CountsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAlarmsSinceLastQuery_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAlarmsSinceLastQuery *ns1__GetAlarmsSinceLastQuery, _ns1__GetAlarmsSinceLastQueryResponse &ns1__GetAlarmsSinceLastQueryResponse)
{	struct __ns1__GetAlarmsSinceLastQuery_ soap_tmp___ns1__GetAlarmsSinceLastQuery_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetAlarmsSinceLastQuery";
	soap_tmp___ns1__GetAlarmsSinceLastQuery_.ns1__GetAlarmsSinceLastQuery = ns1__GetAlarmsSinceLastQuery;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAlarmsSinceLastQuery_(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAlarmsSinceLastQuery_(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery_, "-ns1:GetAlarmsSinceLastQuery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAlarmsSinceLastQuery_(soap, &soap_tmp___ns1__GetAlarmsSinceLastQuery_, "-ns1:GetAlarmsSinceLastQuery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAlarmsSinceLastQueryResponse)
		return soap_closesock(soap);
	ns1__GetAlarmsSinceLastQueryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAlarmsSinceLastQueryResponse.soap_get(soap, "ns1:GetAlarmsSinceLastQueryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAlarms_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAlarms *ns1__GetAlarms, _ns1__GetAlarmsResponse &ns1__GetAlarmsResponse)
{	struct __ns1__GetAlarms_ soap_tmp___ns1__GetAlarms_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetAlarms";
	soap_tmp___ns1__GetAlarms_.ns1__GetAlarms = ns1__GetAlarms;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAlarms_(soap, &soap_tmp___ns1__GetAlarms_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAlarms_(soap, &soap_tmp___ns1__GetAlarms_, "-ns1:GetAlarms", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAlarms_(soap, &soap_tmp___ns1__GetAlarms_, "-ns1:GetAlarms", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetAlarmsResponse)
		return soap_closesock(soap);
	ns1__GetAlarmsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAlarmsResponse.soap_get(soap, "ns1:GetAlarmsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__MountedMolds_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__MountedMolds *ns1__MountedMolds, _ns1__MountedMoldsResponse &ns1__MountedMoldsResponse)
{	struct __ns1__MountedMolds_ soap_tmp___ns1__MountedMolds_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/MountedMolds";
	soap_tmp___ns1__MountedMolds_.ns1__MountedMolds = ns1__MountedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__MountedMolds_(soap, &soap_tmp___ns1__MountedMolds_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__MountedMolds_(soap, &soap_tmp___ns1__MountedMolds_, "-ns1:MountedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__MountedMolds_(soap, &soap_tmp___ns1__MountedMolds_, "-ns1:MountedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__MountedMoldsResponse)
		return soap_closesock(soap);
	ns1__MountedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MountedMoldsResponse.soap_get(soap, "ns1:MountedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Measures_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Measures *ns1__Measures, _ns1__MeasuresResponse &ns1__MeasuresResponse)
{	struct __ns1__Measures_ soap_tmp___ns1__Measures_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/Measures";
	soap_tmp___ns1__Measures_.ns1__Measures = ns1__Measures;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__Measures_(soap, &soap_tmp___ns1__Measures_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Measures_(soap, &soap_tmp___ns1__Measures_, "-ns1:Measures", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Measures_(soap, &soap_tmp___ns1__Measures_, "-ns1:Measures", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__MeasuresResponse)
		return soap_closesock(soap);
	ns1__MeasuresResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__MeasuresResponse.soap_get(soap, "ns1:MeasuresResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CumulCounts_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__CumulCounts *ns1__CumulCounts, _ns1__CumulCountsResponse &ns1__CumulCountsResponse)
{	struct __ns1__CumulCounts_ soap_tmp___ns1__CumulCounts_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/CumulCounts";
	soap_tmp___ns1__CumulCounts_.ns1__CumulCounts = ns1__CumulCounts;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__CumulCounts_(soap, &soap_tmp___ns1__CumulCounts_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CumulCounts_(soap, &soap_tmp___ns1__CumulCounts_, "-ns1:CumulCounts", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CumulCounts_(soap, &soap_tmp___ns1__CumulCounts_, "-ns1:CumulCounts", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__CumulCountsResponse)
		return soap_closesock(soap);
	ns1__CumulCountsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CumulCountsResponse.soap_get(soap, "ns1:CumulCountsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReadenMolds_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ReadenMolds *ns1__ReadenMolds, _ns1__ReadenMoldsResponse &ns1__ReadenMoldsResponse)
{	struct __ns1__ReadenMolds_ soap_tmp___ns1__ReadenMolds_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ReadenMolds";
	soap_tmp___ns1__ReadenMolds_.ns1__ReadenMolds = ns1__ReadenMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ReadenMolds_(soap, &soap_tmp___ns1__ReadenMolds_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReadenMolds_(soap, &soap_tmp___ns1__ReadenMolds_, "-ns1:ReadenMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReadenMolds_(soap, &soap_tmp___ns1__ReadenMolds_, "-ns1:ReadenMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ReadenMoldsResponse)
		return soap_closesock(soap);
	ns1__ReadenMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ReadenMoldsResponse.soap_get(soap, "ns1:ReadenMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__EjectedMolds_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__EjectedMolds *ns1__EjectedMolds, _ns1__EjectedMoldsResponse &ns1__EjectedMoldsResponse)
{	struct __ns1__EjectedMolds_ soap_tmp___ns1__EjectedMolds_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/EjectedMolds";
	soap_tmp___ns1__EjectedMolds_.ns1__EjectedMolds = ns1__EjectedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__EjectedMolds_(soap, &soap_tmp___ns1__EjectedMolds_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__EjectedMolds_(soap, &soap_tmp___ns1__EjectedMolds_, "-ns1:EjectedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__EjectedMolds_(soap, &soap_tmp___ns1__EjectedMolds_, "-ns1:EjectedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__EjectedMoldsResponse)
		return soap_closesock(soap);
	ns1__EjectedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__EjectedMoldsResponse.soap_get(soap, "ns1:EjectedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetMoldsInSampleTable_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetMoldsInSampleTable *ns1__GetMoldsInSampleTable, _ns1__GetMoldsInSampleTableResponse &ns1__GetMoldsInSampleTableResponse)
{	struct __ns1__GetMoldsInSampleTable_ soap_tmp___ns1__GetMoldsInSampleTable_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetMoldsInSampleTable";
	soap_tmp___ns1__GetMoldsInSampleTable_.ns1__GetMoldsInSampleTable = ns1__GetMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetMoldsInSampleTable_(soap, &soap_tmp___ns1__GetMoldsInSampleTable_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetMoldsInSampleTable_(soap, &soap_tmp___ns1__GetMoldsInSampleTable_, "-ns1:GetMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetMoldsInSampleTable_(soap, &soap_tmp___ns1__GetMoldsInSampleTable_, "-ns1:GetMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__GetMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetMoldsInSampleTableResponse.soap_get(soap, "ns1:GetMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeMountedMolds_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeMountedMolds *ns1__ChangeMountedMolds, _ns1__ChangeMountedMoldsResponse &ns1__ChangeMountedMoldsResponse)
{	struct __ns1__ChangeMountedMolds_ soap_tmp___ns1__ChangeMountedMolds_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeMountedMolds";
	soap_tmp___ns1__ChangeMountedMolds_.ns1__ChangeMountedMolds = ns1__ChangeMountedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeMountedMolds_(soap, &soap_tmp___ns1__ChangeMountedMolds_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeMountedMolds_(soap, &soap_tmp___ns1__ChangeMountedMolds_, "-ns1:ChangeMountedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeMountedMolds_(soap, &soap_tmp___ns1__ChangeMountedMolds_, "-ns1:ChangeMountedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeMountedMoldsResponse)
		return soap_closesock(soap);
	ns1__ChangeMountedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeMountedMoldsResponse.soap_get(soap, "ns1:ChangeMountedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AddEjectedMolds_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AddEjectedMolds *ns1__AddEjectedMolds, _ns1__AddEjectedMoldsResponse &ns1__AddEjectedMoldsResponse)
{	struct __ns1__AddEjectedMolds_ soap_tmp___ns1__AddEjectedMolds_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/AddEjectedMolds";
	soap_tmp___ns1__AddEjectedMolds_.ns1__AddEjectedMolds = ns1__AddEjectedMolds;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__AddEjectedMolds_(soap, &soap_tmp___ns1__AddEjectedMolds_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AddEjectedMolds_(soap, &soap_tmp___ns1__AddEjectedMolds_, "-ns1:AddEjectedMolds", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AddEjectedMolds_(soap, &soap_tmp___ns1__AddEjectedMolds_, "-ns1:AddEjectedMolds", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__AddEjectedMoldsResponse)
		return soap_closesock(soap);
	ns1__AddEjectedMoldsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__AddEjectedMoldsResponse.soap_get(soap, "ns1:AddEjectedMoldsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__EraseMoldsInSampleTable_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__EraseMoldsInSampleTable *ns1__EraseMoldsInSampleTable, _ns1__EraseMoldsInSampleTableResponse &ns1__EraseMoldsInSampleTableResponse)
{	struct __ns1__EraseMoldsInSampleTable_ soap_tmp___ns1__EraseMoldsInSampleTable_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/EraseMoldsInSampleTable";
	soap_tmp___ns1__EraseMoldsInSampleTable_.ns1__EraseMoldsInSampleTable = ns1__EraseMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__EraseMoldsInSampleTable_(soap, &soap_tmp___ns1__EraseMoldsInSampleTable_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__EraseMoldsInSampleTable_(soap, &soap_tmp___ns1__EraseMoldsInSampleTable_, "-ns1:EraseMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__EraseMoldsInSampleTable_(soap, &soap_tmp___ns1__EraseMoldsInSampleTable_, "-ns1:EraseMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__EraseMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__EraseMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__EraseMoldsInSampleTableResponse.soap_get(soap, "ns1:EraseMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeMoldsInSampleTable_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeMoldsInSampleTable *ns1__ChangeMoldsInSampleTable, _ns1__ChangeMoldsInSampleTableResponse &ns1__ChangeMoldsInSampleTableResponse)
{	struct __ns1__ChangeMoldsInSampleTable_ soap_tmp___ns1__ChangeMoldsInSampleTable_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeMoldsInSampleTable";
	soap_tmp___ns1__ChangeMoldsInSampleTable_.ns1__ChangeMoldsInSampleTable = ns1__ChangeMoldsInSampleTable;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeMoldsInSampleTable_(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeMoldsInSampleTable_(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable_, "-ns1:ChangeMoldsInSampleTable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeMoldsInSampleTable_(soap, &soap_tmp___ns1__ChangeMoldsInSampleTable_, "-ns1:ChangeMoldsInSampleTable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeMoldsInSampleTableResponse)
		return soap_closesock(soap);
	ns1__ChangeMoldsInSampleTableResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeMoldsInSampleTableResponse.soap_get(soap, "ns1:ChangeMoldsInSampleTableResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVersions_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetVersions *ns1__GetVersions, _ns1__GetVersionsResponse &ns1__GetVersionsResponse)
{	struct __ns1__GetVersions_ soap_tmp___ns1__GetVersions_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/GetVersions";
	soap_tmp___ns1__GetVersions_.ns1__GetVersions = ns1__GetVersions;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetVersions_(soap, &soap_tmp___ns1__GetVersions_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetVersions_(soap, &soap_tmp___ns1__GetVersions_, "-ns1:GetVersions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetVersions_(soap, &soap_tmp___ns1__GetVersions_, "-ns1:GetVersions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__GetVersionsResponse)
		return soap_closesock(soap);
	ns1__GetVersionsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetVersionsResponse.soap_get(soap, "ns1:GetVersionsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ChangeSamples_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ChangeSamples *ns1__ChangeSamples, _ns1__ChangeSamplesResponse &ns1__ChangeSamplesResponse)
{	struct __ns1__ChangeSamples_ soap_tmp___ns1__ChangeSamples_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1/wstm11/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://www.tiama-inspection.com/ChangeSamples";
	soap_tmp___ns1__ChangeSamples_.ns1__ChangeSamples = ns1__ChangeSamples;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ChangeSamples_(soap, &soap_tmp___ns1__ChangeSamples_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ChangeSamples_(soap, &soap_tmp___ns1__ChangeSamples_, "-ns1:ChangeSamples", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ChangeSamples_(soap, &soap_tmp___ns1__ChangeSamples_, "-ns1:ChangeSamples", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__ChangeSamplesResponse)
		return soap_closesock(soap);
	ns1__ChangeSamplesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ChangeSamplesResponse.soap_get(soap, "ns1:ChangeSamplesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
